api:
  server_port: 8080
decks:
  suits:
    - CLUBS
    - DIAMONDS
    - HEARTS
    - SPADES
  values:
    - ACE
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - TEN
    - JACK
    - QUEEN
    - KING